# Go to https://alacritty.org/config-alacritty.html for config details
[general]
import=["~/.config/alacritty/vauge.toml"]
[window]
decorations="Full"
opacity=1.0
blur=false
title="Alacritty Terminal"
[scrolling]
history=3000
[cursor]
vi_mode_style={shape="Block", blinking="Off"}
[font]
size=10
normal={family="JetBrainsMono Nerd Font", style="Regular"}
bold={family="JetBrainsMono Nerd Font", style="Bold"}
italic={family="JetBrainsMono Nerd Font", style="Regular"}
bold_italic={family="JetBrainsMono Nerd Font", style="Bold"}
